// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf8pQRDBk6rrZmxQAqOAHIPJM2ONbvc3k',
    appId: '1:730667356039:web:3e57cbc8685fc503d30d22',
    messagingSenderId: '730667356039',
    projectId: 'glinex-b6d54',
    authDomain: 'glinex-b6d54.firebaseapp.com',
    storageBucket: 'glinex-b6d54.firebasestorage.app',
    measurementId: 'G-CETZNK9XX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcBA71udppA9hTVLWeI7UBQqHt01x3YYo',
    appId: '1:730667356039:android:c09da4fc847900b7d30d22',
    messagingSenderId: '730667356039',
    projectId: 'glinex-b6d54',
    storageBucket: 'glinex-b6d54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmXVbcqEqEkdwoRrZZaMXbxAn1_GbrTKE',
    appId: '1:730667356039:ios:2e735c2cc271be92d30d22',
    messagingSenderId: '730667356039',
    projectId: 'glinex-b6d54',
    storageBucket: 'glinex-b6d54.firebasestorage.app',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmXVbcqEqEkdwoRrZZaMXbxAn1_GbrTKE',
    appId: '1:730667356039:ios:2e735c2cc271be92d30d22',
    messagingSenderId: '730667356039',
    projectId: 'glinex-b6d54',
    storageBucket: 'glinex-b6d54.firebasestorage.app',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAf8pQRDBk6rrZmxQAqOAHIPJM2ONbvc3k',
    appId: '1:730667356039:web:3ae775843294fa99d30d22',
    messagingSenderId: '730667356039',
    projectId: 'glinex-b6d54',
    authDomain: 'glinex-b6d54.firebaseapp.com',
    storageBucket: 'glinex-b6d54.firebasestorage.app',
    measurementId: 'G-F8SBB366ZB',
  );
}
